import paramiko
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('192.168.1.6', username='ramzy', password='Ramzy123', timeout=5)
sftp = ssh.open_sftp()
sftp.put('test.mjs', '/home/ramzy/ramscraft/backend/test.mjs')
sftp.close()
ssh.exec_command("cd /home/ramzy/ramscraft/backend && rm -f prisma/dev.db && npx prisma db push")
import time
time.sleep(5)
stdin, stdout, stderr = ssh.exec_command("cd /home/ramzy/ramscraft/backend && pkill node; nohup node dist/index.js > backend.log 2>&1 &")
stdout.channel.recv_exit_status()
time.sleep(2)
stdin, stdout, stderr = ssh.exec_command("cd /home/ramzy/ramscraft/backend && node test.mjs")
print(stdout.read().decode())
err = stderr.read().decode()
if err: print("STDERR:", err)
ssh.close()
