import React, { useEffect, useState, useRef } from 'react';
import { useParams } from 'react-router-dom';
import axios from 'axios';
import { Globe, Trash, UploadCloud, Download, Plus } from 'lucide-react';
import { useServersStore } from '../../store/useServersStore';

export const Worlds = () => {
    const { id } = useParams();
    const server = useServersStore(s => s.servers.find(srv => srv.id === id));
    const [worlds, setWorlds] = useState<any[]>([]);
    const [isGenerating, setIsGenerating] = useState(false);
    const zipInputRef = useRef<HTMLInputElement>(null);

    const fetchWorlds = async () => {
        try {
            const res = await axios.get(`/api/servers/${id}/worlds`);
            setWorlds(res.data);
        } catch (e) {
            console.error(e);
        }
    };

    useEffect(() => { fetchWorlds(); }, [id]);

    const handleDelete = async (world: string) => {
        if (!confirm('Are you sure you want to delete world: ' + world + '? This is irreversible.')) return;
        try {
            await axios.delete(`/api/servers/${id}/files?path=/${world}`);
            fetchWorlds();
        } catch (e) {
            console.error('Delete failed');
        }
    };

    const handleDownload = (world: string) => {
        window.open(`/api/servers/${id}/files?path=/${world}&action=download`, '_blank');
    };

    const handleZipUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
        if (!e.target.files || e.target.files.length === 0) return;
        const formData = new FormData();
        formData.append('file', e.target.files[0]);
        
        try {
            await axios.post(`/api/servers/${id}/files/extract?path=/`, formData, {
                headers: { 'Content-Type': 'multipart/form-data' }
            });
            fetchWorlds();
            alert('World imported successfully.');
        } catch (err) {
            alert('Import failed');
        }
        if (e.target) e.target.value = '';
    };

    const handleGenerate = async () => {
        if (server?.status !== 'OFFLINE') {
            alert('Server must be OFFLINE to safely generate a new world.');
            return;
        }

        const name = prompt('WARNING: Generating a new world will change your active world. Existing folders with the same name will be temporarily preserved as a backup, but you should download them first to be safe.\n\nEnter new world name (e.g. world):', 'world');
        
        if (!name) return;

        setIsGenerating(true);
        try {
            const res = await axios.post(`/api/servers/${id}/worlds/generate`, { worldName: name });
            if (res.data.backupCreated) {
                alert(`Existing world backed up. The new '${name}' world is configured and will be generated by Minecraft when you next Start the server.`);
            } else {
                alert(`The new '${name}' world is configured and will be generated by Minecraft when you next Start the server.`);
            }
            fetchWorlds();
        } catch (err: any) {
            alert(err.response?.data?.error || 'Generation failed');
        } finally {
            setIsGenerating(false);
        }
    };

    return (
        <div className="max-w-5xl space-y-6">
            <div className="glass-panel rounded-xl overflow-hidden">
                <div className="p-5 border-b border-white/[0.04] bg-white/[0.02] flex items-center justify-between">
                    <div>
                        <h3 className="text-lg font-semibold text-white">Worlds</h3>
                        <p className="text-sm text-slate-400 mt-1">Manage server worlds (folders containing level.dat).</p>
                    </div>
                    <div className="flex gap-2">
                        <input type="file" accept=".zip" ref={zipInputRef} onChange={handleZipUpload} className="hidden" />
                        <button onClick={() => zipInputRef.current?.click()} className="glass-button px-4 py-2 flex items-center gap-2">
                            <UploadCloud size={16}/> Import ZIP
                        </button>
                        <button onClick={handleGenerate} disabled={isGenerating} className="glass-button bg-blue-500/10 text-blue-400 border-blue-500/20 hover:bg-blue-500/20 px-4 py-2 flex items-center gap-2">
                            <Plus size={16}/> {isGenerating ? 'Preparing...' : 'Generate New World'}
                        </button>
                    </div>
                </div>
                
                <div className="bg-black/20">
                    <table className="w-full text-left text-sm text-slate-300">
                        <thead className="bg-black/40 border-b border-white/[0.04]">
                            <tr>
                                <th className="px-6 py-3 font-semibold text-slate-400">Folder Name</th>
                                <th className="px-6 py-3 text-right font-semibold text-slate-400">Actions</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-white/[0.04]">
                            {worlds.length === 0 ? (
                                <tr>
                                    <td colSpan={2} className="px-6 py-12 text-center flex flex-col items-center">
                                        <div className="w-12 h-12 bg-black/40 rounded-full flex items-center justify-center mb-4 border border-white/5">
                                            <Globe size={20} className="text-slate-500" />
                                        </div>
                                        <p className="text-slate-400 font-medium">No worlds found. Start the server to generate one.</p>
                                    </td>
                                </tr>
                            ) : worlds.map((w, i) => (
                                <tr key={i} className="hover:bg-white/[0.02] transition-colors group">
                                    <td className="px-6 py-4 flex items-center gap-3">
                                        <div className="bg-green-500/10 p-2 rounded-lg border border-green-500/20">
                                            <Globe size={18} className="text-green-400" />
                                        </div>
                                        <div>
                                            <span className="font-semibold text-white block">{w.name}</span>
                                            <span className="text-xs text-slate-500">{new Date(w.modifiedAt).toLocaleString()}</span>
                                        </div>
                                    </td>
                                    <td className="px-6 py-4 text-right space-x-2">
                                        <button onClick={() => handleDownload(w.name)} className="glass-button p-2 text-slate-400 hover:text-white inline-flex opacity-0 group-hover:opacity-100 transition-opacity" title="Download">
                                            <Download size={14} />
                                        </button>
                                        <button onClick={() => handleDelete(w.name)} className="glass-button bg-red-500/10 text-red-400 border-red-500/20 hover:bg-red-500/20 hover:text-red-300 p-2 inline-flex items-center gap-2 opacity-0 group-hover:opacity-100 transition-opacity" title="Delete">
                                            <Trash size={14} />
                                        </button>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    );
};
