export enum ServerStatus {
  OFFLINE = 'OFFLINE',
  RECOVERING = 'RECOVERING',
  STARTING = 'STARTING',
  ONLINE = 'ONLINE',
  STOPPING = 'STOPPING',
  CRASHED = 'CRASHED',
  EULA_PENDING = 'EULA_PENDING'
}
